{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rootcx-core.fullname" . }}
  labels:
    {{- include "rootcx-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "rootcx-core.databaseUrl" . | quote }}
  {{- if .Values.jwtSecret }}
  ROOTCX_JWT_SECRET: {{ .Values.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.masterKey }}
  ROOTCX_MASTER_KEY: {{ .Values.masterKey | quote }}
  {{- end }}
  {{- if (include "rootcx-core.oidcClientSecret" .) }}
  ROOTCX_OIDC_CLIENT_SECRET: {{ include "rootcx-core.oidcClientSecret" . | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
{{- end }}
